[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    '@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
    '@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol',
    '@layerzerolabs/lz-evm-messagelib-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/messagelib',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    'solidity-bytes-utils/=lib/solidity-bytes-utils/',
]

[rpc_endpoints]
base = "wss://base-rpc.publicnode.com"
base_sepolia = "wss://base-sepolia.drpc.org"
zircuit = "wss://zircuit-mainnet.drpc.org"
arbitrum = "wss://arbitrum-one-rpc.publicnode.com"
